import type { Metadata } from "next";
import { Roboto } from 'next/font/google'

import { Header } from "@/components";
import { ReactQueryProvider } from "@/lib/react-query-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Coinpulse",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} box-border min-h-screen px-6 py-4 sm:px-16 sm:py-8 flex flex-col gap-10`}
      >
        <ReactQueryProvider>
          <Header />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
